//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelTrack.Resources {
    using System;
    using System.Reflection;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FuelTrack.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string TitleApp {
            get {
                return ResourceManager.GetString("TitleApp", resourceCulture);
            }
        }

        internal static string TitleHome {
            get {
                return ResourceManager.GetString("TitleHome", resourceCulture);
            }
        }

        internal static string TitleOverview {
            get {
                return ResourceManager.GetString("TitleOverview", resourceCulture);
            }
        }

        internal static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }

        internal static string TitleCar {
            get {
                return ResourceManager.GetString("TitleCar", resourceCulture);
            }
        }

        internal static string TitleCarAdd {
            get {
                return ResourceManager.GetString("TitleCarAdd", resourceCulture);
            }
        }

        internal static string TitleCarEdit {
            get {
                return ResourceManager.GetString("TitleCarEdit", resourceCulture);
            }
        }

        internal static string TitleFuelUp {
            get {
                return ResourceManager.GetString("TitleFuelUp", resourceCulture);
            }
        }

        internal static string TitleFuelUpAdd {
            get {
                return ResourceManager.GetString("TitleFuelUpAdd", resourceCulture);
            }
        }

        internal static string TitleFuelUpEdit {
            get {
                return ResourceManager.GetString("TitleFuelUpEdit", resourceCulture);
            }
        }

        internal static string ButtonSettings {
            get {
                return ResourceManager.GetString("ButtonSettings", resourceCulture);
            }
        }

        internal static string ButtonRefresh {
            get {
                return ResourceManager.GetString("ButtonRefresh", resourceCulture);
            }
        }

        internal static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }

        internal static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }

        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }

        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }

        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }

        internal static string ButtonCarAdd {
            get {
                return ResourceManager.GetString("ButtonCarAdd", resourceCulture);
            }
        }

        internal static string ButtonCarEdit {
            get {
                return ResourceManager.GetString("ButtonCarEdit", resourceCulture);
            }
        }

        internal static string ButtonCarDelete {
            get {
                return ResourceManager.GetString("ButtonCarDelete", resourceCulture);
            }
        }

        internal static string ButtonFuelUpAdd {
            get {
                return ResourceManager.GetString("ButtonFuelUpAdd", resourceCulture);
            }
        }

        internal static string ButtonFuelUpEdit {
            get {
                return ResourceManager.GetString("ButtonFuelUpEdit", resourceCulture);
            }
        }

        internal static string ButtonFuelUpDelete {
            get {
                return ResourceManager.GetString("ButtonFuelUpDelete", resourceCulture);
            }
        }

        internal static string HeaderAppearance {
            get {
                return ResourceManager.GetString("HeaderAppearance", resourceCulture);
            }
        }

        internal static string HeaderUnits {
            get {
                return ResourceManager.GetString("HeaderUnits", resourceCulture);
            }
        }

        internal static string LabelTheme {
            get {
                return ResourceManager.GetString("LabelTheme", resourceCulture);
            }
        }

        internal static string LabelDistance {
            get {
                return ResourceManager.GetString("LabelDistance", resourceCulture);
            }
        }

        internal static string LabelFuel {
            get {
                return ResourceManager.GetString("LabelFuel", resourceCulture);
            }
        }

        internal static string LabelCar {
            get {
                return ResourceManager.GetString("LabelCar", resourceCulture);
            }
        }

        internal static string LabelAlias {
            get {
                return ResourceManager.GetString("LabelAlias", resourceCulture);
            }
        }

        internal static string LabelVendor {
            get {
                return ResourceManager.GetString("LabelVendor", resourceCulture);
            }
        }

        internal static string LabelModel {
            get {
                return ResourceManager.GetString("LabelModel", resourceCulture);
            }
        }

        internal static string LabelYear {
            get {
                return ResourceManager.GetString("LabelYear", resourceCulture);
            }
        }

        internal static string LabelPlate {
            get {
                return ResourceManager.GetString("LabelPlate", resourceCulture);
            }
        }

        internal static string LabelFuelType {
            get {
                return ResourceManager.GetString("LabelFuelType", resourceCulture);
            }
        }

        internal static string LabelNote {
            get {
                return ResourceManager.GetString("LabelNote", resourceCulture);
            }
        }

        internal static string LabelDate {
            get {
                return ResourceManager.GetString("LabelDate", resourceCulture);
            }
        }

        internal static string LabelTime {
            get {
                return ResourceManager.GetString("LabelTime", resourceCulture);
            }
        }

        internal static string LabelQuantity {
            get {
                return ResourceManager.GetString("LabelQuantity", resourceCulture);
            }
        }

        internal static string LabelAmount {
            get {
                return ResourceManager.GetString("LabelAmount", resourceCulture);
            }
        }

        internal static string LabelPartial {
            get {
                return ResourceManager.GetString("LabelPartial", resourceCulture);
            }
        }

        internal static string OptionThemeDefault {
            get {
                return ResourceManager.GetString("OptionThemeDefault", resourceCulture);
            }
        }

        internal static string OptionThemeLight {
            get {
                return ResourceManager.GetString("OptionThemeLight", resourceCulture);
            }
        }

        internal static string OptionThemeDark {
            get {
                return ResourceManager.GetString("OptionThemeDark", resourceCulture);
            }
        }

        internal static string OptionUnitDistanceKilometers {
            get {
                return ResourceManager.GetString("OptionUnitDistanceKilometers", resourceCulture);
            }
        }

        internal static string OptionUnitDistanceMiles {
            get {
                return ResourceManager.GetString("OptionUnitDistanceMiles", resourceCulture);
            }
        }

        internal static string OptionUnitFuelLiters {
            get {
                return ResourceManager.GetString("OptionUnitFuelLiters", resourceCulture);
            }
        }

        internal static string OptionUnitFuelGallons {
            get {
                return ResourceManager.GetString("OptionUnitFuelGallons", resourceCulture);
            }
        }

        internal static string OptionUnitFuelKilowattHours {
            get {
                return ResourceManager.GetString("OptionUnitFuelKilowattHours", resourceCulture);
            }
        }

        internal static string OptionFuelTypeUnknown {
            get {
                return ResourceManager.GetString("OptionFuelTypeUnknown", resourceCulture);
            }
        }

        internal static string OptionFuelTypeGasoline {
            get {
                return ResourceManager.GetString("OptionFuelTypeGasoline", resourceCulture);
            }
        }

        internal static string OptionFuelTypeDiesel {
            get {
                return ResourceManager.GetString("OptionFuelTypeDiesel", resourceCulture);
            }
        }

        internal static string OptionFuelTypePetroleum {
            get {
                return ResourceManager.GetString("OptionFuelTypePetroleum", resourceCulture);
            }
        }

        internal static string OptionFuelTypeNaturalGas {
            get {
                return ResourceManager.GetString("OptionFuelTypeNaturalGas", resourceCulture);
            }
        }

        internal static string OptionFuelTypeEthanol {
            get {
                return ResourceManager.GetString("OptionFuelTypeEthanol", resourceCulture);
            }
        }

        internal static string OptionFuelTypeBioDiesel {
            get {
                return ResourceManager.GetString("OptionFuelTypeBioDiesel", resourceCulture);
            }
        }

        internal static string OptionFuelTypeHydrogen {
            get {
                return ResourceManager.GetString("OptionFuelTypeHydrogen", resourceCulture);
            }
        }

        internal static string OptionFuelTypeElectricity {
            get {
                return ResourceManager.GetString("OptionFuelTypeElectricity", resourceCulture);
            }
        }

        internal static string OptionFuelTypeOther {
            get {
                return ResourceManager.GetString("OptionFuelTypeOther", resourceCulture);
            }
        }

        internal static string MessageEmptyCars {
            get {
                return ResourceManager.GetString("MessageEmptyCars", resourceCulture);
            }
        }
    }
}
